# Generated by Django 5.2.3 on 2025-12-10 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="name",
            field=models.CharField(
                blank=True,
                help_text="Display name (can be different from username)",
                max_length=150,
            ),
        ),
    ]
